services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rawgDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  seeder:
    container_name: seeder
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_URL: mysql://root:rootpassword@mysql:3306/rawgDatabase

  rawg-server:
    container_name: rawg-server
    build:
      context: ./rawg-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_URL: mysql://root:rootpassword@mysql:3306/rawgDatabase
    ports:
      - "5000:5000"

  rawg-client:
    container_name: rawg-client
    build:
      context: ./rawg-client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - rawg-server
    ports:
      - "3000:3000"
    
volumes:
  mysql_data: